    // ------------------------------------------------------------------------------
    // <auto-generated>
    // Bu kod araç tarafından oluşturuldu.
    // Çalışma Zamanı Sürümü:4.0.30319.42000
    // 
    // Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
    // kod yeniden oluşturulursa kaybolur.
    // </auto-generated>
    // ------------------------------------------------------------------------------

    using System.Diagnostics;
    using Microsoft.VisualBasic;
    using Microsoft.VisualBasic.CompilerServices;


    namespace EMAR.My
    {

        [System.Runtime.CompilerServices.CompilerGenerated()]
        [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal sealed partial class MySettings : System.Configuration.ApplicationSettingsBase
        {

            private static MySettings defaultInstance = (MySettings)Synchronized(new MySettings());

            #region My.Settings Otomatik Kaydetme İşlevi
            /* TODO ERROR: Skipped IfDirectiveTrivia
            #If _MyType = "WindowsForms" Then
            *//* TODO ERROR: Skipped DisabledTextTrivia
                Private Shared addedHandler As Boolean

                Private Shared addedHandlerLockObject As New Object

                <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
                Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
                    If My.Application.SaveMySettingsOnExit Then
                        My.Settings.Save()
                    End If
                End Sub
            *//* TODO ERROR: Skipped EndIfDirectiveTrivia
            #End If
            */
            #endregion

            public static MySettings Default
            {
                get
                {

                    /* TODO ERROR: Skipped IfDirectiveTrivia
                    #If _MyType = "WindowsForms" Then
                    *//* TODO ERROR: Skipped DisabledTextTrivia
                                   If Not addedHandler Then
                                        SyncLock addedHandlerLockObject
                                            If Not addedHandler Then
                                                AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                                                addedHandler = True
                                            End If
                                        End SyncLock
                                    End If
                    *//* TODO ERROR: Skipped EndIfDirectiveTrivia
                    #End If
                    */
                    return defaultInstance;
                }
            }

            [System.Configuration.UserScopedSetting()]
            [DebuggerNonUserCode()]
            [System.Configuration.DefaultSettingValue("\"\"")]
            public string Ayar
            {
                get
                {
                    return Conversions.ToString(this["Ayar"]);
                }
                set
                {
                    this["Ayar"] = value;
                }
            }
        }
    }

    namespace EMAR.My
    {

        [HideModuleName()]
        [DebuggerNonUserCode()]
        [System.Runtime.CompilerServices.CompilerGenerated()]
        internal static class MySettingsProperty
        {

            [System.ComponentModel.Design.HelpKeyword("My.Settings")]
            internal static MySettings Settings
            {
                get
                {
                    return MySettings.Default;
                }
            }
        }
    }